---
title: "Additional Code"
author: "Charlotte Imbert"
output: html_document
date: "2025-01-16"
---

```{r}
# ADDITIONAL ANALYSES NOT INCLUDED IN REPORT
completed_data |>
  ggplot(aes(x = strikes, y = swing_length, group = strikes)) +
  geom_boxplot(aes(fill = strikes)
  ) +
  labs(title = "Swing Length by Strike Number",
       x = "Strikes",
       y = "Swing Length") +
  theme_minimal() +
  coord_cartesian(ylim = c(2.5,12)) +
  theme(legend.position = "none")
ggsave("strike_swing_boxplot.jpg", height = 10, width = 10, dpi = 300)

completed_data |>
  ggplot(aes(x = strikes, y = bat_speed, group = strikes)) +
  geom_boxplot(aes(fill = strikes)
  ) +
  labs(title = "Bat Speed by Strike Number",
       x = "Strikes",
       y = "Bat Speed") +
  theme_minimal() +
  coord_cartesian(ylim = c(25, 90)) +
  theme(legend.position = "none")
ggsave("strike_speed_boxplot.jpg", height = 10, width = 10, dpi = 300)
```

```{r}
# PERMUTATION TESTS
# Comparison of mean bat speed by pitch type: H_0: mean bat speed is the same across pitch types, H_A: there is a difference in mean bat speed across pitch types
# calculate observed group means

#BAT SPEED FIRST

observed_group_means<- completed_data |>
  group_by(pitch_type) |>
  summarise(mean_bat_speed_obs = mean(bat_speed))

# group variance - test statistic
observed_stat<- var(observed_group_means$mean_bat_speed_obs)
```

```{r}
set.seed(3)
n_perms <- 1000
speed_perm_stats <- numeric(n_perms)
 for (i in 1:n_perms) {
   shuffled_data<- completed_data |>
     mutate(shuffled_pitch_type = sample(pitch_type)) |>
     group_by(shuffled_pitch_type) |>
     summarise(mean_bat_speed_shuffled = mean(bat_speed))
   
   speed_perm_stats[i]<- var(shuffled_data$mean_bat_speed_shuffled)
 }
```

```{r}
set.seed(3)
p_value <- mean(speed_perm_stats >= observed_stat)

print(paste("Observed Test Statistic:", observed_stat))
print(paste("P-value:", p_value))
```

```{r}
speed_perm_stats_df <- data.frame(speed_perm_stats = speed_perm_stats)

# Plot the null distribution with the observed statistic
ggplot(speed_perm_stats_df, aes(x = speed_perm_stats)) +
  geom_histogram(bins = 30, fill = "lavender", color = "black", alpha = 0.7) +
  geom_vline(xintercept = observed_stat, color = "red1", linetype = "dashed", linewidth = 0.7) +
  labs(
    title = "Bat Speed by Pitch Type - Null Distribution (Permuted Data)",
    x = "Variance of Group Means",
  ) +
  theme_minimal()
ggsave("speed_permutation.jpg", width = 10, height = 10, dpi = 300)
```

```{r}
#SWING LENGTH

observed_group_means<- completed_data |>
  group_by(pitch_type) |>
  summarise(mean_swing_length_obs = mean(swing_length))

# group variance - test statistic
observed_stat<- var(observed_group_means$mean_swing_length_obs)
```

```{r}
set.seed(3)
n_perms <- 1000
swing_perm_stats <- numeric(n_perms)
 for (i in 1:n_perms) {
   shuffled_data<- completed_data |>
     mutate(shuffled_pitch_type = sample(pitch_type)) |>
     group_by(shuffled_pitch_type) |>
     summarise(mean_swing_length_shuffled = mean(swing_length))
   
   swing_perm_stats[i]<- var(shuffled_data$mean_swing_length_shuffled)
 }
```

```{r}
set.seed(3)
p_value <- mean(swing_perm_stats >= observed_stat)
print(paste("Observed Test Statistic:", observed_stat))
print(paste("P-value:", p_value))
```

```{r}
swing_perm_stats_df <- data.frame(swing_perm_stats = swing_perm_stats)

ggplot(swing_perm_stats_df, aes(x = swing_perm_stats)) +
  geom_histogram(bins = 30, fill = "cyan3", color = "black", alpha = 0.7) +
  geom_vline(xintercept = observed_stat, color = "red1", linetype = "dashed", linewidth = 0.7) +
  labs(
    title = "Swing Length by Pitch Type - Null Distribution (Permuted Data)",
    x = "Variance of Group Means",
  ) +
  theme_minimal()
ggsave("swing_permutation.jpg", width = 10, height = 10, dpi = 300)
```

```{r}
# create a new column for spin axis groups (groups spin axis into 4 categories, corresponding to spin direction)
completed_data <- completed_data |>
 mutate(spin_axis_group = case_when(
    spin_axis >= 315 | spin_axis < 45  ~ "Topspin",          # 315°–45°
    spin_axis >= 45 & spin_axis < 135  ~ "Right-Side Spin",  # 45°–135°
    spin_axis >= 135 & spin_axis < 225 ~ "Backspin",         # 135°–225°
    spin_axis >= 225 & spin_axis < 315 ~ "Left-Side Spin"    # 225°–315°
  ))
```

```{r}
# observe the distribution of spin axis
ggsave("spin_axis_dist.jpg", height = 10, width = 10, dpi = 300)
ggplot(completed_data, aes(x = spin_axis_group, fill = spin_axis_group)) +
  geom_bar(color = "black") +
  scale_fill_manual(
    name = "Spin Axis",
    values = c(
      "Backspin" = "aquamarine",
      "Left-Side Spin" = "deepskyblue3",
      "Right-Side Spin" = "magenta4",
      "Topspin" = "darkslateblue"
    ),
    labels = c(
      "Backspin" = "135°-225°",
      "Left-Side Spin" = "225°-315°",
      "Right-Side Spin" = "45°-135°",
      "Topspin" = "315°-45°"
    )
  ) +
  labs(
    title = "Distribution of Spin Axis Groups",
    x = "Spin Axis Group",
    y = "Count"
  ) +
  theme_minimal()
```

```{r}
ggplot(completed_data, aes(x = spin_axis_group, y = swing_length, fill = spin_axis_group)) +
  geom_boxplot() +
  scale_fill_manual(
    name = "Spin Direction",
    values = c(
      "Backspin" = "aquamarine",
      "Left-Side Spin" = "deepskyblue3",
      "Right-Side Spin" = "magenta4",
      "Topspin" = "darkslateblue"
    )
    ) +
  labs(title = "Swing Length by Spin Direction",
       x = "Spin Direction",
       y = "Swing Length") +
  theme_minimal() +
  theme(legend.position = "none") +
  coord_cartesian(ylim = c(3, 10))
ggsave("boxplot_swing_by_spin_axis.jpg", width = 10, height = 10, dpi = 300)
```

```{r}
#ANOVA
anova_swing <- aov(swing_length ~ spin_axis_group, data = completed_data)

# Summary of ANOVA
summary(anova_swing)
```

```{r}
# Tukey's HSD
tukey_result <- TukeyHSD(anova_swing)
print(tukey_result)
plot(tukey_result)
```

```{r}
ggplot(completed_data, aes(x = spin_axis_group, y = bat_speed, fill = spin_axis_group)) +
  geom_boxplot() +
    scale_fill_manual(
    name = "Spin Direction",
    values = c(
      "Backspin" = "aquamarine",
      "Left-Side Spin" = "deepskyblue3",
      "Right-Side Spin" = "magenta4",
      "Topspin" = "darkslateblue"
    )
    ) +
  labs(title = "Bat Speed by Spin Direction",
       x = "Spin Axis Quadrant",
       y = "Bat Speed") +
  theme_minimal() +
  theme(legend.position = "none") +
  coord_cartesian(ylim = c(50, 90))
ggsave("boxplot_speed_by_spin_axis.jpg", width = 10, height = 10, dpi = 300)
```

```{r}
# ANOVA
anova_speed <- aov(bat_speed ~ spin_axis_group, data = completed_data)
summary(anova_speed)
```

```{r}
# Tukey's HSD
tukey_result <- TukeyHSD(anova_speed)
print(tukey_result)
plot(tukey_result)

# differences for speed are not significant
```


```{r}
t.test(swing_length ~ batter_pitcher_opposite, data = completed_data)
```

```{r}
t.test(bat_speed ~ batter_pitcher_opposite, data = completed_data)
```

```{r}
var.test(swing_length ~ batter_pitcher_opposite, data = completed_data)
```

```{r}
var.test(bat_speed ~ batter_pitcher_opposite, data = completed_data)
```

```{r}
ggplot(completed_data, aes(x = batter_pitcher_opposite, y = swing_length, group = batter_pitcher_opposite)) +
  geom_boxplot(aes(fill= batter_pitcher_opposite)) +
  labs(
    title = "Swing Length and Handedness",
    x = "Handedness (1 = same, 0 = opposite)",
    y = "Swing Length"
  ) +
  theme_minimal()
ggsave("handedness_swing_length.jpg", height = 10, width = 10, dpi = 300)
```

```{r}
ggplot(completed_data, aes(x = batter_pitcher_opposite, y = bat_speed, group = batter_pitcher_opposite)) +
  geom_boxplot(aes(fill= batter_pitcher_opposite)) +
  labs(
    title = "Bat Speed and Handedness",
    x = "Handedness (1 = same, 0 = opposite)",
    y = "Bat Speed"
  ) +
  theme_minimal()
ggsave("handedness_speed.jpg", height = 10, width = 10, dpi = 300)
```

```{r}
completed_data |>
ggplot() +
  geom_hex(aes(x = release_speed, y = swing_length), bins = 100) +
  scale_fill_viridis_c() +
  labs(
    title = "Swing Length vs. Release Speed",
    x = "Release Speed",
    y = "Swing Length",
    fill = "Count"
  ) +
  theme_minimal()
ggsave("swing_length_release_speed.jpg", height = 10, width = 10, dpi = 300)
```

```{r}
completed_data |>
ggplot() +
  geom_hex(aes(x = release_speed, y = bat_speed), bins = 200) +
  scale_fill_viridis_c() +
  labs(
    title = "Bat Speed vs. Release Speed",
    x = "Release Speed",
    y = "Bat Speed",
    fill = "Count"
  ) +
  theme_minimal()
ggsave("bat_speed_release_speed.jpg", height = 10, width = 10, dpi = 300)
```

```{r}
completed_data |>
ggplot() +
  geom_hex(aes(x = release_spin_rate, y = swing_length), bins = 100) +
  scale_fill_viridis_c() +
  labs(
    title = "Swing Length vs. Release Spin Rate",
    x = "Release Spin Rate",
    y = "Swing Length",
    fill = "Count"
  ) +
  theme_minimal()
ggsave("swing_length_release_spin.jpg", height = 10, width = 10, dpi = 300)
```

```{r}
completed_data |>
ggplot() +
  geom_hex(aes(x = release_spin_rate, y = bat_speed), bins = 200) +
  scale_fill_viridis_c() +
  labs(
    title = "Bat Speed vs. Release Spin Rate",
    x = "Release Spin Rate",
    y = "Bat Speed",
    fill = "Count"
  ) +
  theme_minimal()
ggsave("bat_speed_release_spin.jpg", height = 10, width = 10, dpi = 300)
```

```{r}
completed_data |>
ggplot() +
  geom_hex(aes(x = pitch_combined, y = swing_length), bins = 100) +
  scale_fill_viridis_c() +
  labs(
    title = "Swing Length vs. Pitch Combined",
    x = "Pitch Combined",
    y = "Swing Length",
    fill = "Count"
  ) +
  theme_minimal()
ggsave("swing_length_pitch_combined.jpg", height = 10, width = 10, dpi = 300)
```

```{r}
completed_data |>
ggplot() +
  geom_hex(aes(x = pitch_combined, y = bat_speed), bins = 200) +
  scale_fill_viridis_c() +
  labs(
    title = "Bat Speed vs. Pitch Combined",
    x = "Pitch Combined",
    y = "Bat Speed",
    fill = "Count"
  ) +
  theme_minimal()
ggsave("bat_speed_pitch_combined.jpg", height = 10, width = 10, dpi = 300)
```